### ISSUE TITLE
Would you please tell how to test the webservice ?

### ISSUE THREAD

**Issue by shuilidy922** [ccunarro/OrdersBackend#1]
I generated a war file and installed it to tomcat webapps directory mywebapp, but when i input localhost:8080/mywebapp, it doesn't work, shows 404 error.

And I have see tomcat webapp management page, the service is loaded succcessfully.

So could you tell me the simplest way to test webservice ?

**Comment by shuilidy922** [comment]
I input this URL: http://localhost:8080/shuyun/customers=1

And get the error :
WARN : org.springframework.web.servlet.PageNotFound - No mapping found for HTTP
request with URI [/shuyun/customers=1] in DispatcherServlet with name 'appServle
t'


Would you please give a help ?

**Comment by shuilidy922** [comment]
Sorry, I find out the right way, since I am new hand to this, please forgive me.
The right URL is : http://localhost:8080/shuyun/customers/1

It fail by JDBC connection now, I will set up mysql and try then.

**Comment by ccunarro** [comment]
shuilidy922  ok its fine, sometimes configuring is complicated
